version: 2.1
jobs:
  build:
    docker:
      - image: 'circleci/node:latest'
      - image: 'circleci/mongo:latest'
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - run:
        name: Wait for Mongo to start
        command: dockerize -wait tcp://127.0.0.1:27017 -timeout 120s
      - run:
        name: Running server in background
        command: npm run start
        background: true
      - run: npm run test